### ISSUE TITLE
0.7.0 Doesn't Compile On Julia 1.7

### ISSUE THREAD

**Issue by JoshuaBillson** [rafaqz/Rasters.jl#451]
I'm trying to import Rasters 0.7.0 into a Pluto notebook running Julia 1.7.3, but I get a compilation error with the following output:

```julia
ERROR: LoadError: UndefVarError: @assume_effects not defined
Stacktrace:
 [1] include(mod::Module, _path::String)
   @ Base ./Base.jl:418
 [2] include(x::String)
   @ Rasters ~/.julia/packages/Rasters/phuM5/src/Rasters.jl:1
 [3] top-level scope
   @ ~/.julia/packages/Rasters/phuM5/src/Rasters.jl:117
 [4] include
   @ ./Base.jl:418 [inlined]
 [5] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1318
 [6] top-level scope
   @ none:1
 [7] eval
   @ ./boot.jl:373 [inlined]
 [8] eval(x::Expr)
   @ Base.MainInclude ./client.jl:453
 [9] top-level scope
   @ none:1
in expression starting at /Users/jmbillson/.julia/packages/Rasters/phuM5/src/methods/rasterize.jl:889
in expression starting at /Users/jmbillson/.julia/packages/Rasters/phuM5/src/methods/rasterize.jl:889
in expression starting at /Users/jmbillson/.julia/packages/Rasters/phuM5/src/Rasters.jl:1
```

I've confirmed that downgrading to 0.6.3 fixes the problem.

**Comment by rafaqz** [comment]
Hmm yes its seems I've not t9tally intentionally stopped supporting anything below 1.8.

(You should probably update to 1.9 though, its much better)

But honestly my dev time is stretched thin, the test suit is huge and slow so running it on 1.6 as well is a pain. 

So all up supporting older versions is annoying and no personal benefit to me at all.

If someone wants to do the necessary work I would accept a PR, probably adding Compat.jl? But its not lekely I will have time to do that, if I ever use 1.7 again I will just use Rasters 0.6.

**Comment by JoshuaBillson** [comment]
If Rasters isn't going to be supporting anything below 1.8 going forward, perhaps Project.toml should reflect this? Would it be possible to set things up so that 0.6 is automatically selected for users below 1.8, with 0.7 and above for everyone else?

Maybe adding the following to [compat] would work:
```
julia = ">= 1.8"
```

**Comment by rafaqz** [comment]
Yeah thats what I mean.

But we also have to yank the current version from the registry if we do that.

**Comment by rafaqz** [comment]
0.7 is yanked, just waiting for it to be merged
https://github.com/JuliaRegistries/General/pull/84197

If you want to support it with Compat, go for it.

**Comment by JoshuaBillson** [comment]
I can now confirm that the correct version is installed for Julia 1.7. Since we were able to yank 0.7.0 from the registry, I think requiring 1.8 and above is the best solution going forward.
